[window]
decorations = "None"
startup_mode = "Fullscreen"

[font]
normal = { family = "SeriousShanns Nerd Font Mono", style = "Regular" }
size = 12

[colors.primary]
foreground = "#dfdfdf"
background = "#142a35"

[colors]
cursor = { text = "#142a35", cursor = "#34cb62" }
footer_bar = { foreground = "#142a35", background = "#34cb62" }
selection = { text = "#142a35", background = "#34cb62" }

[colors.search]
matches = { foreground = "#142a35", background = "#34cb62" }

[colors.normal]
red = "#f43557"
green = "#34cb62"

[cursor]
unfocused_hollow = false
